STREAM_SLEEP_SEC = 0.0
ROLLING_WINDOW = 20
ENTRY_THRESHOLD = 0.08
EXIT_THRESHOLD = 0.00
TRANSACTION_COST = 0.01
SLIPPAGE = 0.005

MODEL_TYPE = "online"
TASK_TYPE = "regression"

INITIAL_CAPITAL = 100000.0
POSITION_SIZE = 1

SESSION_SIZE = 1380
MAX_BATCH_SESSIONS = 5
USE_BATCH_SESSION_FEEDBACK = True

BATCH_HORIZON_K = 300

BATCH_MODEL_TYPE = "xgboost_reg"
# linear_reg, logistic, xgboost_reg, xgboost_clf, lightgbm_reg, lightgbm_clf

BATCH_TASK_TYPE = "regression"
# regression or classification

USE_GPU = True
LIGHTGBM_GPU_BACKEND = "gpu"

ONLINE_HORIZON = 5
MIN_WARMUP_TICKS = 0

USE_SIGNAL_SMOOTHING = True
SIGNAL_SMOOTHING_ALPHA = 0.2